### ISSUE TITLE
Rabbit error

### ISSUE THREAD

**Issue by abitofgorgonzola** [tumblenet/beta.tumblenet.cu.cc#12]
# Expected behavior and actual behavior

You're not meant to be a giant rabbit.
# Steps to reproduce the problem

Fix the moon.
# Specifications like the version of the project, operating system, or hardware

Mind-o-matic
![wallace-and-gromit-the-curse-of-the-were-rabbit-transformation-scene-review](https://cloud.githubusercontent.com/assets/22398495/19731512/924fde3a-9b95-11e6-8100-3e634ada0a9c.jpg)
![curse-of-the-were-rabbit-disneyscreencaps_com-5401](https://cloud.githubusercontent.com/assets/22398495/19731514/94215b26-9b95-11e6-8d47-83860ece0928.jpg)

**Comment by tumble1999** [comment]
i know someone who will fix this...

**Comment by abitofgorgonzola** [comment]
Who
