### ISSUE TITLE
Button doesn't work

### ISSUE THREAD

**Issue by abitofgorgonzola** [tumblenet/beta.tumblenet.cu.cc#14]
# Expected behavior and actual behavior
Button on website links to nothing.
# Steps to reproduce the problem

# Specifications like the version of the project, operating system, or hardware
Go to beta.tumblenet.tk. Click on the button in the middle of the home screen. See results.
![issue 1](https://cloud.githubusercontent.com/assets/22398495/19863360/de4ac80a-9f8b-11e6-85e1-0534e686f675.PNG)
![issue 2](https://cloud.githubusercontent.com/assets/22398495/19863363/e1c855a6-9f8b-11e6-959b-ace616570bd6.PNG)

**Comment by tumble1999** [comment]
What button.
Give screenshot

**Comment by tumble1999** [comment]
How can a user end up doing that:
Add something for the button to link to.

**Comment by tumble1999** [comment]
That's not a behaviour

Button on website.

**Comment by tumble1999** [comment]
REASON:trying to link to service URL but services don't have an output (its own page)
